### ISSUE TITLE
missing include

### ISSUE THREAD

**Issue by skye-AL** [ATLFlight/HelloWorld#1] opened 2016-03-09 20:42 UTC
Only have this error if I run make load-bundle:

make[4]: Entering directory `/home/skye-AL/HelloWorld/bundle/build_bundle'
[ 28%] Generating helloworld_app
In file included from ../apps_proc/helloworld.c:34:0:
/home/skye-AL/HelloWorld/bundle/build_bundle/example_interface.h:34:23: fatal error: AEEStdDef.h: No such file or directory
 #include "AEEStdDef.h"

, else it works.

**Comment by julianoes** [comment] 2016-03-23 17:30
@mcharleb Could you please have a look? Could it be that you are using ninja and therefore it works for you?

**Comment by smnogar** [comment] 2016-04-01 13:28
I am also getting this error. I think it has to do with cmake_hexagon. When I modify lines in cmake_hexagon/fastrpc.cmake:

`set(FASTRPC_ARM_LINUX_INCLUDES
    ${HEXAGON_SDK_ROOT}/inc
    ${HEXAGON_SDK_ROOT}/inc/stddef
    ${HEXAGON_SDK_ROOT}/lib/common/rpcmem
    ${HEXAGON_SDK_ROOT}/lib/common/adspmsgd/ship/UbuntuARM_${RELEASE}
    ${HEXAGON_SDK_ROOT}/lib/common/remote/ship/UbuntuARM_${RELEASE}
    )`

to 

`set(FASTRPC_ARM_LINUX_INCLUDES
    -I${HEXAGON_SDK_ROOT}/inc
    -I${HEXAGON_SDK_ROOT}/inc/stddef
    -I${HEXAGON_SDK_ROOT}/lib/common/rpcmem
    -I${HEXAGON_SDK_ROOT}/lib/common/adspmsgd/ship/UbuntuARM_${RELEASE}
    -I${HEXAGON_SDK_ROOT}/lib/common/remote/ship/UbuntuARM_${RELEASE}
    )`

I no longer get the "AEEStdDef.h: No such file or directory" but now get the errors

`/tmp/ccRVtVpJ.o: In function`_example_interface_pls_dtor':
example_interface_stub.c:(.text+0x1c): undefined reference to `remote_handle_close'
/tmp/ccRVtVpJ.o: In function`_example_interface_pls_ctor':
example_interface_stub.c:(.text+0x54): undefined reference to `remote_handle_open'
/tmp/ccRVtVpJ.o: In function`example_interface_skel_invoke':
example_interface_stub.c:(.text+0x13e): undefined reference to `remote_handle_invoke'
/tmp/ccRVtVpJ.o: In function`_stub_method':
example_interface_stub.c:(.text+0x16c): undefined reference to `remote_handle_invoke'
collect2: error: ld returned 1 exit status`

Any suggestions? It looks like it is still not correctly referencing some sort of library or include.

**Comment by mcharleb** [comment] 2016-04-01 13:31
What version of cmake are you using? I need to know to reproduce it.

**Comment by smnogar** [comment] 2016-04-01 13:32
3.2.2

**Comment by mcharleb** [comment] 2016-04-01 13:33
Sorry to take so long to reply. I didn't see this thread earlier.

**Comment by skye-AL** [comment] 2016-04-01 13:36
Thank you for looking at it!, I use 3.4.3.

**Comment by julianoes** [comment] 2016-04-11 06:59
@mcharleb: Can you please look into this?
Or can you give me more pointers what to look at?

**Comment by skye-AL** [comment] 2016-04-11 08:23
To specify the problem: running `make all`, and then `make load` works in the _HelloWorld_ folder, just running the command `make helloworld-load`, in the _HelloWorld/bundle/build_bundle_ folder fails.
Similarly for the dspal tester, the branch _old_example_ not invoking the bundle-build still works.

**Comment by genemerewether** [comment] 2016-04-11 15:35
@mcharleb @julianoes - here's some information from when I was trying to diagnose this problem: it has to do with expansion of the semicolon-separated lists of directories inside cmake into whitespace separated lists in bash. It seems to only affect HelloWorld and DSPAL, and doesn't seem to matter what CMake version. I haven't seen this problem occur with the PX4/Firmware or DriverFramework repositories.

As can be seen with **make --dry-run helloworld-load**, the include directory & flag expansion isn't happening properly. Only the first of the include directories (see below) receives a flag.

At [cmake_hexagon bundle.cmake line 107](https://github.com/ATLFlight/cmake_hexagon/blob/master/bundle.cmake#L107), the ${QURT_BUNDLE_APP_NAME}_INCLUDE_DIRS variable gets set to a list of include dir strings separated by semicolons, with a -I at the very beginning. However, when expanded by bash, at least on my system, this becomes the command below, with cmake passing -I"first include dir" "second include dir" and so on.

When I manually fix the include directory flags, a similar but separate problem also arises at [cmake_hexagon fastrpc.cmake line 84](https://github.com/ATLFlight/cmake_hexagon/blob/master/fastrpc.cmake#L84). Two problems occur here: the space after RELEASE} on line 84 turns into backslash space (to escape it), which prevents the rest of the line from being read correctly. Also, rpcmem.a is not getting the right include flags (either -l:"explicit path to library file" or -L"dir" -l"lib name"

When these three formatting errors are corrected, everything builds properly. Similar errors come up in the DSPAL test code compilation.

`cd /home/mereweth/src/HelloWorld/bundle && arm-linux-gnueabihf-gcc -I/home/mereweth/src/HelloWorld/bundle/build_bundle /home/mereweth/Qualcomm/Hexagon_SDK/2.0/inc /home/mereweth/Qualcomm/Hexagon_SDK/2.0/inc/stddef /home/mereweth/Qualcomm/Hexagon_SDK/2.0/lib/common/rpcmem /home/mereweth/Qualcomm/Hexagon_SDK/2.0/lib/common/adspmsgd/ship/UbuntuARM_Debug /home/mereweth/Qualcomm/Hexagon_SDK/2.0/lib/common/remote/ship/UbuntuARM_Debug -o /home/mereweth/src/HelloWorld/bundle/build_bundle/helloworld_app ../apps_proc/helloworld.c /home/mereweth/src/HelloWorld/bundle/build_bundle/example_interface_stub.c -L/home/mereweth/Qualcomm/Hexagon_SDK/2.0/lib/common/remote/ship/UbuntuARM_Debug\ -ladsprpc /home/mereweth/Qualcomm/Hexagon_SDK/2.0/lib/common/rpcmem/UbuntuARM_Debug/rpcmem.a`

**Comment by SamChenzx** [comment] 2016-04-11 20:23
@genemerewether I'm wondering if the command you've posted really works in your system?

**Comment by genemerewether** [comment] 2016-04-11 20:26
@SamChenzx which command? The long gcc command I posted is the incorrectly formatted one that cmake generates

**Comment by SamChenzx** [comment] 2016-04-11 20:30
@genemerewether Yes, the long one "cd /home/mereweth/src/HelloWorld/bundle && arm-linux-gnueabihf-gcc ...", regardless of Helloworld and DSPAL, have you ever tried other example projects inside the SDK, such as calculator, did it work?

**Comment by genemerewether** [comment] 2016-04-11 20:43
@SamChenzx 

For an example of the type of changes that could fix the command and let you build the helloworld app (but not fix the underlying issue with CMake/bash)

Run this from the HelloWorld/bundle folder

`arm-linux-gnueabihf-gcc -I./build_bundle -I${HEXAGON_SDK_ROOT}/inc -I${HEXAGON_SDK_ROOT}/inc/stddef -I${HEXAGON_SDK_ROOT}/lib/common/rpcmem -I${HEXAGON_SDK_ROOT}/lib/common/adspmsgd/ship/UbuntuARM_Debug -I${HEXAGON_SDK_ROOT}/lib/common/remote/ship/UbuntuARM_Debug -o ./build_bundle/helloworld_app ../apps_proc/helloworld.c ./build_bundle/example_interface_stub.c -L${HEXAGON_SDK_ROOT}/lib/common/remote/ship/UbuntuARM_Debug -ladsprpc -l:${HEXAGON_SDK_ROOT}/lib/common/rpcmem/UbuntuARM_Debug/rpcmem.a`

I haven't tried other projects in the SDK. If you're interested in PX4 Firmware or DriverFramework, both compile and build fine for the flight board with the latest BSP and aDSP image.

**Comment by SamChenzx** [comment] 2016-04-11 21:29
@genemerewether 
Thanks for your reply! I tried your command then send libexample_interface_skel.so, libhelloworld.so and helloworld_app to /usr/share/data/adsp/ and /home/linaro/ by adb push the follow is what I got from snapdragon flight. It seems there are still some bugs, have you ever run into this?
root@linaro-developer:/home/linaro# ./helloworld_app 
Asking DSP to say hello
/home/cberg/Desktop/r00015/oe-core/build/tmp-eglibc/work/cortexa8hf-vfp-neon-linux-gnueabi/adsprpc/1.0-r0/adsprpc-1.0/src/fastrpc_apps_user.c:136:failed to create tls key/home/cberg/Desktop/r00015/oe-core/build/tmp-eglibc/work/cortexa8hf-vfp-neon-linux-gnueabi/adsprpc/1.0-r0/adsprpc-1.0/src/listener_android.c:112:listener using ion heap: -1
/home/cberg/Desktop/r00015/oe-core/build/tmp-eglibc/work/cortexa8hf-vfp-neon-linux-gnueabi/adsprpc/1.0-r0/adsprpc-1.0/src/listener_android.c:129:listener protocol failure -1
/home/cberg/Desktop/r00015/oe-core/build/tmp-eglibc/work/cortexa8hf-vfp-neon-linux-gnueabi/adsprpc/1.0-r0/adsprpc-1.0/src/listener_android.c:133::error: -1: 0 == (nErr = __QAIC_HEADER(adsp_listener_next_invoke)( ctx, nErr, 0, 0, &ctx, &handle, &sc, bufs->inbufs, inBufsAllocated, bufs->inbufLenReqs, MAX_BUFS, bufs->outbufLenReqs, MAX_BUFS))
/home/cberg/Desktop/r00015/oe-core/build/tmp-eglibc/work/cortexa8hf-vfp-neon-linux-gnueabi/adsprpc/1.0-r0/adsprpc-1.0/src/listener_android.c:192:listener thread exiting with code -1
/home/cberg/Desktop/r00015/oe-core/build/tmp-eglibc/work/cortexa8hf-vfp-neon-linux-gnueabi/adsprpc/1.0-r0/adsprpc-1.0/src/listener_android.c:194:listener thread failed to cleanly shutdown.  This is ok durring process exit.
/home/cberg/Desktop/r00015/oe-core/build/tmp-eglibc/work/cortexa8hf-vfp-neon-linux-gnueabi/adsprpc/1.0-r0/adsprpc-1.0/src/fastrpc_apps_user.c:159:exit: closing /dev/adsprpc-smd, rpc errors are expected.

**Comment by mcharleb** [comment] 2016-04-12 01:40
HelloWorld has been fixed (finally). There were several issues in the bundle.cmake including the fact that using add_custom_command vs add_custom_target did not cause the helloworld_app to be built until helloworld-load was made.

It required an updated cmake_hexagon and should now work. Sorry for the delay on getting it fixed.

**Closed as completed** 2016-04-12 01:40 UTC

**Comment by mcharleb** [comment] 2016-04-12 01:45
@genemerewether I have updated HelloWorld and it should work now without modification.

The "errors" you see above are regrettably not errors and are "expected
output". This will be fixed in an updated version of the ARM libraries in
the SDK. @jywilson 

If you run mini-dm (its in the tools dir of SDK), you should see the
HelloWorld output.

**Comment by julianoes** [comment] 2016-04-12 07:30
@mcharleb I cross tested this. Seems all fixed for me. Thanks!

**Comment by SamChenzx** [comment] 2016-04-12 14:04
Thanks for your reply, I truly agree those "errors" are not really errors,
and see the Hello World output, it works fine.

**Comment by skye-AL** [comment] 2016-04-12 20:39
Nice! Thanks!
